name: node-rtsp-streaming

networks:
  default:
    name: node-rtsp-streaming

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 2000:2000
      - 3000:3000
      - 8000:8000
      - 4000:4000
    command: nodemon index.js
